# Generated by Django 5.0.1 on 2025-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
